Pandas

In [20]:
import numpy as np

In [21]:
# import pandas as pd
from numpy.random import randn
import pandas as pd

In [22]:
# labels = ['a','b','c']
# my_data = [10,20,30]
# arr = np.array(my_data)
# d = {'a':10,'b':20,'c':30}
np.random.seed(101)

In [23]:
# pd.Series(data = my_data)

In [24]:
import numpy as np
import pandas as pd
df = pd.DataFrame(
    np.random.randn(5, 4),['A', 'B', 'C', 'D', 'E'],['W','X','Y','Z'])

In [25]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [26]:
booldf = df>0

In [32]:
data = df[booldf]

In [33]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [34]:
df[df['W']>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [35]:
data.groupby("Pclass").agg({
  "Age": "mean",
  "Fare": "mean",
  "Survived": "sum"

})

KeyError: 'Pclass'

PANDAS GROUPBY

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = {'Company': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
        'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
        'sales': [200, 120, 340, 124, 243, 350]}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

In [ ]:
import numpy as np
import pandas as pd
byComp = df.groupby('Company')

In [ ]:
byComp['sales'].mean()

In [ ]:
byComp.sum().loc['FB']

In [ ]:
byComp.sum().loc['FB']

  Joining

In [ ]:
import numpy as np
import pandas as pd

left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3']},
                     index = ['B0', 'B1', 'B2', 'B3'])

right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                      'B': ['B0', 'B1', 'B2', 'B3']},
                      index = ['B0', 'B1', 'B2', 'B3'])

In [31]:
left.join(right, how='outer', lsuffix='_left', rsuffix='_right')

   key_left   A key_right   B
B0       K0  A0        K0  B0
B1       K1  A1        K1  B1
B2       K2  A2        K2  B2
B3       K3  A3        K3  B3

Pandas - Operation

In [37]:
import numpy as np 
import pandas as pd

In [38]:
df = pd.DataFrame({'col1':[1,2,3,4],
                   'col2':[444,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [39]:
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [47]:
len(df['col2'].unique())

3

In [49]:
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [46]:
df[(df['col1']>2) & (df['col2'] == 444)]

   col1  col2 col3
3     4   444  xyz